// VidaPlus - modulo agenda
function tt(t){t=String(t||'');const i=t.indexOf(': ');return t.length>90&&i>6&&i<80?[t.slice(0,i),t.slice(i+2)]:[t,'']}
const TASK_CATS={personal:'Personal',familia:'Familia',compras:'Para comprar',presupuesto:'Presupuesto',trabajo:'Trabajo'};
function taskItem(x){let due=x.vencimiento?x.vencimiento.slice(0,10):x.fecha,hora=x.vencimiento?x.vencimiento.slice(11,16):null,overdue=!x.hecha&&due<today();return `<div class="item"><button class="check ${x.hecha?'done':''}" aria-label="${x.hecha?'Marcar como pendiente':'Marcar como hecha'}" onclick="act('toggleTarea',{id:'${x.id}',hecha:${!x.hecha}})">${x.hecha?'✓':''}</button><div class="item-main ${x.hecha?'strike':''}">${esc(tt(x.texto)[0])}${x.categoria&&x.categoria!=='personal'?'<span class="cat-badge cat-'+x.categoria+'">'+(TASK_CATS[x.categoria]||x.categoria)+'</span>':''}${overdue?'<span class="badge-overdue">Atrasada</span>':''}${tt(x.texto)[1]?'<div class="task-det" onclick="this.classList.toggle(\'open\')">'+esc(tt(x.texto)[1])+'</div>':''}<div class="sub">${hora?fmt(due)+' · '+hora:fmt(x.fecha)}${x.alerta?' · WhatsApp':''}${x.monto?' · '+money(x.monto):''}</div></div><button class="more" aria-label="Editar" onclick="openForm('tareas','${x.id}')">•••</button></div>`}
function calendarWidget(){if(!calSel)calSel=today();let y=calMonth.getFullYear(),m=calMonth.getMonth(),first=new Date(y,m,1),startDow=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),monthName=calMonth.toLocaleDateString('es-AR',{month:'long',year:'numeric'}),cells='';for(let i=0;i<startDow;i++)cells+='<div class="cal-cell empty"></div>';for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,dt=DB.tareas.filter(x=>x.fecha===ds),full=dt.length&&dt.every(x=>x.hecha),isToday=ds===today(),isSel=ds===calSel;cells+=`<button class="cal-cell ${isToday?'today':''} ${isSel?'sel':''}" onclick="calPick('${ds}')" aria-label="${d} de ${monthName}"><span>${d}</span>${dt.length?`<i class="dot ${full?'full':''}"></i>`:''}</button>`}let selTasks=DB.tareas.filter(x=>x.fecha===calSel);return `<div class="cal"><div class="cal-head"><button onclick="calNav(-1)" aria-label="Mes anterior">‹</button><b>${monthName}</b><button onclick="calNav(1)" aria-label="Mes siguiente">›</button></div><div class="cal-grid">${['L','M','X','J','V','S','D'].map(d=>`<span class="cal-dow">${d}</span>`).join('')}${cells}</div><div class="cal-agenda">${selTasks.length?selTasks.map(taskItem).join(''):`<div class="empty">${calSel===today()?'Nada agendado para hoy.':'Sin tareas ese día.'}</div>`}</div></div>`}
function calNav(dir){calMonth=new Date(calMonth.getFullYear(),calMonth.getMonth()+dir,1);render()}
function calPick(d){calSel=d;render()}
let calWeek=null;
function weekMonday(ds){const x=new Date(ds+'T12:00:00');x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function calWeekNav(dir){if(!calWeek)calWeek=weekMonday(calSel||today());calWeek=new Date(calWeek.getTime());calWeek.setDate(calWeek.getDate()+7*dir);calSel=ymd(calWeek);render()}
function weekStripHtml(){if(!calSel)calSel=today();if(!calWeek)calWeek=weekMonday(calSel);const dows=['L','M','X','J','V','S','D'];let cells='';for(let i=0;i<7;i++){const d=new Date(calWeek.getTime());d.setDate(d.getDate()+i);const ds=ymd(d),dt=DB.tareas.filter(x=>(x.vencimiento?x.vencimiento.slice(0,10):x.fecha)===ds),pend=dt.some(x=>!x.hecha);cells+=`<button class="wk-day ${ds===today()?'today':''} ${ds===calSel?'sel':''}" onclick="calSel='${ds}';render()" aria-label="${d.toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}"><small>${dows[i]}</small><b>${d.getDate()}</b><i class="dot ${dt.length&&!pend?'full':''}" style="${dt.length?'':'visibility:hidden'}"></i></button>`}const fin=new Date(calWeek.getTime());fin.setDate(fin.getDate()+6);const rango=calWeek.toLocaleDateString('es-AR',{day:'numeric',month:'short'})+' – '+fin.toLocaleDateString('es-AR',{day:'numeric',month:'short'});return `<div class="cal"><div class="cal-head"><button onclick="calWeekNav(-1)" aria-label="Semana anterior">‹</button><b>${rango}</b><button onclick="calWeekNav(1)" aria-label="Semana siguiente">›</button></div><div class="wk-strip">${cells}</div></div>`}
function agendaDelDia(){const lista=DB.tareas.filter(x=>(x.vencimiento?x.vencimiento.slice(0,10):x.fecha)===calSel).sort((a,b)=>(a.vencimiento||a.fecha).localeCompare(b.vencimiento||b.fecha));const titulo=calSel===today()?'Hoy':new Date(calSel+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'});return `<div class="agenda-list"><div class="agenda-title">${titulo}</div>${lista.length?lista.map(taskItem).join(''):'<div class="empty">Nada agendado. Anotá algo arriba.</div>'}</div>`}
