// VidaPlus - modulo auth
async function loginAuth(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),m=document.querySelector('#authMsg');try{AUTH=await api('login',{usuario:d.usuario,password:d.password});location.reload()}catch(err){m.textContent=err.message;m.style.color='#a52c28'}}
const SUPPORT_WHATSAPP='5493816669116';
const LINK_PAGO_UNICO='https://mpago.la/32eQM78';
const LINK_SUSCRIPCION_PRO='https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=241e23199e874113ab06b16202e57b74';
function renderAuth(){document.querySelector('.top').style.display='none';const sb=document.getElementById('sidebar');if(sb)sb.style.display='none';$('#main').innerHTML=`<section style="min-height:78dvh;display:grid;place-items:center;padding:18px 0"><div style="width:min(420px,100%);background:#fff;border:1px solid #E4EAF0;border-radius:28px;padding:28px;box-shadow:0 18px 45px #0A1F4418"><div style="display:flex;align-items:center;gap:12px;margin-bottom:8px"><span style="width:52px;height:52px;display:block"><svg viewBox="0 0 512 512" aria-label="VidaPlus"><defs><linearGradient id="lgL" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#BFDDFB"/><stop offset="1" stop-color="#C9EBD2"/></linearGradient></defs><rect width="512" height="512" rx="120" fill="#14161C"/><path d="M138 160 256 354 374 160" fill="none" stroke="url(#lgL)" stroke-width="58" stroke-linecap="round" stroke-linejoin="round"/><path d="M396 322v78M357 361h78" stroke="#F8EFCB" stroke-width="28" stroke-linecap="round"/></svg></span><span style="font-weight:800;font-size:25px">VidaPlus</span></div><p style="margin:0 0 24px;color:#617084">Ingresá a tu espacio personal.</p><form id="authForm"><label class="form-field">Usuario<input name="usuario" placeholder="Tu usuario" required autocomplete="username"></label><label class="form-field">Contraseña<input name="password" type="password" placeholder="Tu contraseña" required minlength="8" autocomplete="current-password"></label><button style="width:100%;border:0;border-radius:14px;padding:14px;background:#FFB45A;color:#0A1F44;font-weight:900" type="submit">Entrar</button></form><p id="authMsg" style="margin-top:14px;color:#617084;font-size:12px">Ingresá con tu usuario y contraseña.</p><button type="button" onclick="olvideClaveUI()" style="background:none;border:0;color:#617084;font-size:12px;text-decoration:underline;cursor:pointer;padding:0;margin-top:6px">¿Olvidaste tu contraseña?</button><a href="https://wa.me/${SUPPORT_WHATSAPP}?text=${encodeURIComponent('Hola, tengo problemas para entrar a VidaPlus')}" target="_blank" rel="noopener" style="display:block;margin-top:16px;text-align:center;background:#F0EEDF;color:#25332B;border-radius:13px;padding:12px;font-weight:700;font-size:13px;text-decoration:none">¿Problemas para entrar? Escribinos por WhatsApp</a></div></section>`;document.querySelector('#authForm').onsubmit=loginAuth;}
async function olvideClaveUI(){const email=prompt('Ingresá tu email para recibir el link de recuperación:');if(!email)return;try{await api('solicitarReset',{email});alert('Si ese email tiene una cuenta, te va a llegar un mail con el link para poner una clave nueva. Revisá también Spam.')}catch(e){alert('No se pudo enviar la solicitud: '+e.message)}}
async function load(){try{AUTH=await api('session')}catch(_){renderAuth();return}let ini=(AUTH?.user?.nombre||'').trim().split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase();document.querySelector('.avatar').textContent=ini||'?';const cached=localStorage.getItem('progreso_db');if(cached){try{DB=JSON.parse(cached);render()}catch(_){}}else busy(1);try{DB=await api('getAll');render();localStorage.setItem('progreso_db',JSON.stringify(DB))}catch(e){say(e.message)}finally{busy(0)}loadRutinas();cargarLecturaInicio()}
async function logout(){await api('logout');localStorage.removeItem('progreso_db');location.reload()}
