// VidaPlus - modulo core
const VIEWS={};
function module(kind){const f=VIEWS[kind];return f?f(kind):viewDiario()}
function viewDiario(){let arr=DB.diario;return `<div class="module-head"><h1>Diario</h1><p>Guardá una nota de tu día.</p></div><div class="section"><h2>Notas</h2><button class="link" onclick="openForm('diario')">Agregar nota</button></div><div class="card">${arr.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).map(x=>item(x,'diario',fmt(x.fecha),esc(x.texto))).join('')||'<div class="empty">Escribí cómo estuvo tu día.</div>'}</div>`;}
const API_URL='/api/data';
const LOGO_URL='/app-icon.svg';
document.head.insertAdjacentHTML('beforeend','<link rel="icon" href="/app-icon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap" rel="stylesheet">');
let DB={tareas:[],pesos:[],entrenamientos:[],habitos:[],habitoLogs:[],diario:[],comidas:[]},AUTH=null,view='hub',verArchivados=false,calMonth=new Date(),calSel=null,USERS=[],AI_MONITOR=null;
const $=s=>document.querySelector(s),today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'}),esc=s=>String(s??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x])),fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('es-AR',{day:'numeric',month:'short'});
document.querySelector('.brand').innerHTML='<img src="'+LOGO_URL+'" alt="Logo VidaPlus">VidaPlus';
async function api(action,p={}){let r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({action,...p})});let j=await r.json();if(!j.ok)throw Error(j.error);return j.data}
function busy(x,label){$('#load').classList.toggle('show',x);if(x)$('#loadLabel').textContent=label||'Procesando…'}
function say(x){let t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function local(a,p,r){let map={Tarea:'tareas',Peso:'pesos',Entrenamiento:'entrenamientos',Habito:'habitos',Diario:'diario',Comida:'comidas'},m=a.match(/(Tarea|Peso|Entrenamiento|Habito|Diario)$/),list=m?map[m[1]]:null;if(a.startsWith('add')&&list)DB[list].push(r);if(a.startsWith('update')&&list){let i=DB[list].findIndex(x=>x.id===p.id);if(i>-1)DB[list][i]={...DB[list][i],...r}}if(a.startsWith('delete')&&list){DB[list]=DB[list].filter(x=>x.id!==p.id);if(a==='deleteHabito')DB.habitoLogs=DB.habitoLogs.filter(x=>String(x.habito_id)!==String(p.id))}if(a==='toggleTarea'){let x=DB.tareas.find(x=>x.id===p.id);if(x)x.hecha=p.hecha}if(a==='toggleHabitoLog'){let i=DB.habitoLogs.findIndex(x=>String(x.habito_id)===String(p.habito_id)&&x.fecha===p.fecha);if(i>-1)DB.habitoLogs.splice(i,1);else DB.habitoLogs.push({id:'temp',habito_id:p.habito_id,fecha:p.fecha})}if(a==='destacarDiario')DB.diario.forEach(x=>x.destacada=(x.id===p.id?r.destacada:false))}
async function act(a,p,msg){busy(1);try{let r=await api(a,p);local(a,p,r);render();try{localStorage.setItem('progreso_db',JSON.stringify(DB))}catch(_){}if(msg)say(msg);setTimeout(()=>api('getAll').then(x=>{DB=x;render();try{localStorage.setItem('progreso_db',JSON.stringify(DB))}catch(_){}}).catch(()=>{}),700)}catch(e){say(e.message)}finally{busy(0)}}
function item(x,kind,main,sub,check){return `<div class="item">${check?`<button class="check ${x.hecha?'done':''}" aria-label="${x.hecha?'Marcar como pendiente':'Marcar como hecha'}" onclick="act('toggleTarea',{id:'${x.id}',hecha:${!x.hecha}})">${x.hecha?'✓':''}</button>`:''}<div class="item-main">${main}<div class="sub">${sub}</div></div><button class="more" aria-label="Editar" onclick="openForm('${kind}','${x.id}')">•••</button></div>`}
function dashboard(title,value,label,pct=0){return `<div class="module-head"><h1>${title}</h1><p>Tu progreso, a tu ritmo.</p></div><div class="dash"><span class="eyebrow">${label}</span><div class="metric">${value}</div>${pct?`<div class="progress"><i style="--p:${pct}%"></i></div>`:''}</div>`}
function latest(a){return a.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha))[0]}
function render(){let html=view==='hub'?hub():view==='inicio'?home():`<section class="view on">${module(view)}</section>`;$('#main').innerHTML=html;const grupo={hub:'hub',inicio:'inicio',fisico:'inicio',rutina:'inicio',entrenar:'inicio',stats:'inicio',nutricion:'nutricion',motivacion:'motivacion',misa:'motivacion',recordatorios:'recordatorios',finanzas:'finanzas',personas:'personas',bandeja:'bandeja',buscar:'buscar',importar:'importar',config:'config',usuarios:'config',admin_ejercicios:'config'}[view]||'';document.querySelectorAll('.sidebar button').forEach(b=>b.classList.toggle('on',b.dataset.v===grupo))}
function ymd(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function go(v){if(v==='analizar')return quickFoodPhoto();if(v==='motivacion')return goMotivacionInicio();view=v;render();if(v==='config')loadAiMonitoring();if(v==='fisico')loadRutinas();if(v==='finanzas')cargarFinanzas();if(v==='personas')cargarPersonas();if(v==='bandeja')cargarBandeja();if(v==='nutricion')cargarNutricion();if(v==='recordatorios'&&AUTH?.settings?.recordatorios_premium)cargarWhatsappUsage();if(v==='config'&&AUTH?.user?.rol==='admin')cargarWhatsappUsage()}
