// VidaPlus - modulo hub
function hub(){const nombre=esc((AUTH?.user?.nombre||'').split(' ')[0]||'');const premium=!!AUTH?.settings?.recordatorios_premium;return `<section class="view on hub-view tiles-view">
<div class="hub-greet"><span class="date">${new Date().toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'})}</span><h1>Hola, ${nombre}</h1><p class="hub-sub">¿Qué querés hacer hoy?</p></div><div class="gsearch"><input id="gq" placeholder="Buscar en todo: tareas, gastos, personas, notas…" autocomplete="off" onkeydown="if(event.key==='Enter')buscarGlobal(this.value)"><button onclick="buscarGlobal($('#gq').value)" aria-label="Buscar"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg></button></div>${premium||AUTH?.user?.rol==='admin'?homeAgenda():''}
<div class="hub-card food" onclick="go('nutricion')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M4 12h4l2-7 4 14 2-7h4"/></svg></div><div><b>Comida Saludable</b><span>Tu día con calorías, menú semanal, recetas y compras</span></div><span class="hub-arrow">›</span></div>
<div class="hub-card body" onclick="go('inicio')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M4 18 9 12l3 3 6-9 2 3"/></svg></div><div><b>Cuerpo Saludable</b><span>Hábitos, rutinas, peso y bienestar</span></div><span class="hub-arrow">›</span></div>
<div class="hub-card motiv" onclick="go('motivacion')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v17H6.5A2.5 2.5 0 0 0 4 21.5z"/></svg></div><div><b>Motivación</b><span>Evangelio del día, diario y lecturas</span></div><span class="hub-arrow">›</span></div>
<div class="hub-card rem ${premium?'':'locked'}" onclick="go('recordatorios')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/></svg></div><div><b>Recordatorios</b><span>${premium?'Tareas, agenda y avisos por WhatsApp':'Función premium — conocé más'}</span></div>${premium?'<span class="hub-arrow">›</span>':'<span class="hub-lock"><svg viewBox="0 0 24 24"><rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/></svg>Premium</span>'}</div>
<div class="hub-card fin" onclick="go('finanzas')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M3 7h15a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3z"/><path d="M3 7l12-4v4"/><circle cx="17" cy="14" r="1.2"/></svg></div><div><b>Finanzas</b><span>Gastos, ingresos y a dónde se va tu plata</span></div><span class="hub-arrow">›</span></div>
<div class="hub-card pers" onclick="go('personas')"><div class="hub-icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3.5"/><path d="M2.5 20c.6-3.6 3.2-5.5 6.5-5.5s5.9 1.9 6.5 5.5M16 4.5a3.5 3.5 0 0 1 0 7M18 14.8c2 .6 3.2 2.3 3.5 5.2"/></svg></div><div><b>Personas</b><span>Contactos, seguimiento y próximos pasos</span></div><span class="hub-arrow">›</span></div>
<div class="hub-card band" onclick="go('bandeja')"><div class="hub-icon"><svg viewBox="0 0 24 24"><path d="M3 13h5l1.5 3h5L16 13h5"/><path d="M5 5h14l2 8v6H3v-6z"/></svg></div><div><b>Bandeja de entrada</b><span>${bandejaCuenta()?bandejaCuenta()+' para ordenar':'Anotá ideas y pendientes sin pensar dónde van'}</span></div><span class="hub-arrow">›</span></div>
</section>`}
