// VidaPlus - modulo motivacion
VIEWS.misa=function(kind){if(!LECTURA_MISA)return `<div class="module-head"><button class="link" onclick="go('motivacion')">‹ Motivación</button><h1>Lectura del día</h1></div><div class="empty">Buscando la lectura de hoy…</div>`;const l=LECTURA_MISA;const sec=(titulo,obj)=>obj?`<div class="section"><h2>${titulo}</h2></div><div class="card"><p class="sub" style="margin:0 0 10px;font-weight:700">${esc(obj.referencia)}</p><div class="wellbeing-copy" style="margin:0">${esc(obj.texto)}</div></div>`:'';return `<div class="module-head"><button class="link" onclick="go('motivacion')">‹ Motivación</button><h1>Lectura del día</h1><p>${esc(l.fecha)}${l.santo?' · '+esc(l.santo):''}</p></div>${sec('Primera lectura',l.primera_lectura)}${sec('Salmo',l.salmo)}${sec('Evangelio',l.evangelio)}`};
VIEWS.motivacion=function(kind){if(!MOTIVACION_LIBRO_SEL||!MOTIVACION){if(MOTIVACION_LIBROS===null)return `<div class="module-head"><button class="link" onclick="go('hub')">‹ Menú principal</button><h1>Motivación</h1><p>Elegí qué leer hoy.</p></div><div class="empty">Buscando tus libros…</div>`;return `<div class="module-head"><button class="link" onclick="go('hub')">‹ Menú principal</button><h1>Motivación</h1><p>Elegí qué leer hoy.</p></div><div class="item card mot-card mot-lect" style="cursor:pointer" onclick="abrirLecturaMisa()"><div class="item-main">Lectura del día<div class="sub">Misa católica de hoy</div></div><button class="more" aria-label="Ver lectura del día">→</button></div><details class="mod-sec"><summary><h2>Diario</h2><span class="mod-sec-action" onclick="event.stopPropagation()"><button class="link" onclick="openForm('diario')">Agregar nota</button></span></summary><div class="mod-sec-body">${DB.diario.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,5).map(x=>`<div class="item"><button class="check ${x.destacada?'done':''}" aria-label="${x.destacada?'Quitar de Inicio':'Mostrar en Inicio'}" onclick="act('destacarDiario',{id:'${x.id}'})"><svg viewBox="0 0 24 24" style="width:13px;height:13px;stroke:currentColor;fill:${x.destacada?'currentColor':'none'};stroke-width:2"><path d="M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.9-5.2-2.8-5.2 2.8 1-5.9-4.3-4.1 5.9-.9z"/></svg></button><div class="item-main">${fmt(x.fecha)}<div class="sub">${esc(x.texto)}</div></div><button class="more" aria-label="Editar" onclick="openForm('diario','${x.id}')">•••</button></div>`).join('')||'<div class="empty">Escribí cómo estuvo tu día.</div>'}</div></details>${MOTIVACION_LIBROS.length?MOTIVACION_LIBROS.map((b,i)=>`<div class="item card mot-card mot-c${i%4}" style="cursor:pointer" onclick="goMotivacionLibro('${b.archivo}')"><div class="item-main">${esc(b.titulo)}${b.autor?'<div class="sub">'+esc(b.autor)+'</div>':''}<div class="sub">${b.capitulos} capítulo${b.capitulos===1?'':'s'}</div></div><button class="more" aria-label="Elegir libro">→</button></div>`).join(''):'<div class="empty">Todavía no hay libros cargados.</div>'}`}return `<div class="module-head"><button class="link" onclick="goMotivacionInicio()">‹ Libros</button><h1>Motivación</h1><p>${esc(MOTIVACION.libro||'')}${MOTIVACION.autor?' · '+esc(MOTIVACION.autor):''}</p></div><div class="card"><h2 style="margin:0 0 12px">${esc(MOTIVACION.capitulo.titulo||'')}</h2><div class="wellbeing-copy" style="margin:0">${esc(MOTIVACION.capitulo.texto||'')}</div></div><button class="save" style="width:100%;margin-top:16px;border-radius:13px;padding:13px;font-weight:800" onclick="goMotivacionLibro('${MOTIVACION_LIBRO_SEL}')">Otra lectura</button>`};
async function cargarLecturaInicio(){try{LECTURA_MISA=await api('getLecturaMisa')}catch(_){LECTURA_MISA=null}if(view==='inicio'||view==='misa')render()}
let MOTIVACION=null,MOTIVACION_LIBROS=null,MOTIVACION_LIBRO_SEL=null,MOTIVACION_HIST=(()=>{try{return JSON.parse(localStorage.getItem('motivacion_hist')||'[]')}catch{return[]}})();
async function goMotivacionInicio(){MOTIVACION=null;MOTIVACION_LIBRO_SEL=null;view='motivacion';render();busy(1,'Buscando tus libros…');try{MOTIVACION_LIBROS=await api('listBooks')}catch(e){MOTIVACION_LIBROS=[];say(e.message)}finally{busy(0);render()}}
async function goMotivacionLibro(archivo){MOTIVACION_LIBRO_SEL=archivo;busy(1,'Buscando una lectura…');try{MOTIVACION=await api('getMotivacion',{archivo,excluir:MOTIVACION_HIST});MOTIVACION_HIST=[...MOTIVACION_HIST,MOTIVACION.capitulo.titulo].slice(-10);try{localStorage.setItem('motivacion_hist',JSON.stringify(MOTIVACION_HIST))}catch(_){}render()}catch(e){MOTIVACION=null;render();say(e.message)}finally{busy(0)}}
let LECTURA_MISA=null;
async function abrirLecturaMisa(){LECTURA_MISA=null;view='misa';render();try{LECTURA_MISA=await api('getLecturaMisa')}catch(e){say(e.message)}render()}
