// VidaPlus - modulo nutricion
VIEWS.nutricion=function(kind){if(!NUTRI_RECETAS)return `<div class="module-head"><button class="link" onclick="go('hub')">‹ Menú principal</button><h1>Nutrición</h1><p>Menú semanal, recetas y lista de compras.</p></div><div class="empty">Cargando…</div>`;
const DIAS=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const TIPOS=['desayuno','almuerzo','merienda','cena'];
const comidas=(NUTRI_PLAN&&NUTRI_PLAN.comidas)||[];
const ns=AUTH?.nutricion||{};
const misDatosHtml=`<details class="mod-sec"><summary><h2>Mis datos</h2></summary><div class="mod-sec-body"><form onsubmit="guardarPerfilNutricionUI(event)"><label class="form-field">Tipo de dieta<select name="diet_type"><option value="omnivoro" ${ns.diet_type==='omnivoro'?'selected':''}>Omnívoro</option><option value="vegetariano" ${ns.diet_type==='vegetariano'?'selected':''}>Vegetariano</option><option value="vegano" ${ns.diet_type==='vegano'?'selected':''}>Vegano</option><option value="sin_tacc" ${ns.diet_type==='sin_tacc'?'selected':''}>Sin TACC</option><option value="pescetariano" ${ns.diet_type==='pescetariano'?'selected':''}>Pescetariano</option><option value="keto" ${ns.diet_type==='keto'?'selected':''}>Keto</option></select></label><label class="form-field">Personas en el hogar<input name="household_size" type="number" min="1" value="${ns.household_size||1}"></label><label class="form-field">Objetivo calórico diario (opcional)<input name="calorie_goal" type="number" min="0" value="${ns.calorie_goal||''}"></label><button class="save" style="width:100%;margin-top:14px">Guardar</button></form></div></details>`;
const tabsHtml=`<div class="chip-group" style="margin:0 0 14px">${[['miDia','Mi día'],['plan','Planificación'],['recetario','Recetario'],['compras','Compras'],['mealprep','Meal prep']].map(([v,l])=>`<button class="chip ${NUTRI_TAB===v?'on':''}" onclick="nutriTab('${v}')">${l}</button>`).join('')}</div>`;
let body='';
if(NUTRI_TAB==='miDia')body=miDiaHtml();
else if(NUTRI_TAB==='plan')body=nutriPlanHtml(DIAS,TIPOS,comidas);
else if(NUTRI_TAB==='recetario')body=nutriRecetarioHtml();
else if(NUTRI_TAB==='compras')body=nutriComprasHtml();
else body=nutriMealPrepHtml();
return `<div class="module-head"><button class="link" onclick="go('hub')">‹ Menú principal</button><h1>Nutrición</h1><p>Menú semanal, recetas y lista de compras.</p></div>${tabsHtml}${body}${misDatosHtml}`};
let MIDIA=null,MIDIA_FECHA=null,MIDIA_MOM=null,MD_LIST=[],_mdT;
const MOMENTOS=[['desayuno','Desayuno'],['almuerzo','Almuerzo'],['merienda','Merienda'],['cena','Cena'],['snack','Snacks']];
function miDiaFecha(){if(!MIDIA_FECHA)MIDIA_FECHA=today();return MIDIA_FECHA}
function miDiaNav(d){const x=new Date(miDiaFecha()+'T12:00:00');x.setDate(x.getDate()+d);MIDIA_FECHA=ymd(x);MIDIA=null;render();cargarMiDia()}
function miDiaAbrir(mom){MIDIA_MOM=mom;const nom=MOMENTOS.find(m=>m[0]===mom)[1],d=$('#modal');d.innerHTML=`<form method="dialog" onsubmit="return false"><h2>Agregar a ${nom}</h2><div style="display:flex;gap:8px"><input id="mdQ" placeholder="Buscar: pan, milanesa, banana…" oninput="miDiaBuscar(this.value)" autocomplete="off"><input id="mdCant" type="number" step="0.5" min="0.5" value="1" style="width:84px" aria-label="Cantidad de porciones"></div><div class="sub" style="margin:-4px 2px 8px">El número es la cantidad de porciones (1, 0.5, 2…).</div><div id="mdRes" class="md-res"></div><details class="md-new"><summary>No está en la lista: crear alimento</summary><input id="mdNom" placeholder="Nombre, ej: Tarta de la abuela"><input id="mdKcal" type="number" inputmode="numeric" placeholder="Calorías por porción"><input id="mdPor" placeholder="Porción, ej: 1 plato"><label class="inline-check"><input id="mdSave" type="checkbox" checked>Guardar para la próxima</label><button class="save" type="button" style="width:100%;margin-top:6px" onclick="miDiaCrear()">Agregar</button></details><div class="actions" style="margin-top:12px"><button class="cancel" type="button" onclick="$('#modal').close()">Cerrar</button></div></form>`;d.showModal();miDiaBuscar('')}
function miDiaBuscar(q){clearTimeout(_mdT);_mdT=setTimeout(async()=>{let r;try{r=await api('buscarAlimentos',{q})}catch(e){r={alimentos:[],recetas:[]}}MD_LIST=[...r.alimentos.map(x=>({...x,tipo:x.mio?'Mío':''})),...r.recetas.map(x=>({...x,tipo:'Receta'}))];const el=$('#mdRes');if(!el)return;el.innerHTML=MD_LIST.length?MD_LIST.map((x,i)=>`<button type="button" class="md-it" onclick="miDiaElegir(${i})"><span><b>${esc(x.nombre)}</b><small>${esc(x.porcion)}${x.tipo?' · '+x.tipo:''}</small></span><i>${x.kcal} kcal</i></button>`).join(''):'<div class="empty" style="padding:14px">No encontramos eso. Creá el alimento abajo.</div>'},180)}
async function miDiaAdd(item){try{await api('addItemDia',{fecha:miDiaFecha(),momento:MIDIA_MOM,...item});say('Agregado');await cargarMiDia()}catch(e){say(e.message)}}
function miDiaElegir(i){const x=MD_LIST[i];if(!x)return;miDiaAdd({nombre:x.nombre,porcion:x.porcion,kcal:x.kcal,cantidad:Number($('#mdCant').value)||1})}
function miDiaCrear(){const nombre=$('#mdNom').value.trim(),kcal=Number($('#mdKcal').value);if(!nombre||!(kcal>=0)||$('#mdKcal').value==='')return say('Poné nombre y calorías');miDiaAdd({nombre,porcion:$('#mdPor').value.trim()||'1 porción',kcal,cantidad:Number($('#mdCant').value)||1,guardar:$('#mdSave').checked});$('#mdNom').value='';$('#mdKcal').value='';$('#mdPor').value=''}
async function miDiaBorrar(id){try{await api('deleteItemDia',{id});await cargarMiDia()}catch(e){say(e.message)}}
async function miDiaGuardarMenu(mom){const n=prompt('Nombre para este menú (ej: Desayuno de siempre)');if(!n)return;try{await api('guardarMenu',{nombre:n,momento:mom,fecha:miDiaFecha()});say('Menú guardado');await cargarMiDia()}catch(e){say(e.message)}}
function miDiaMenus(mom){MIDIA_MOM=mom;const ms=(MIDIA&&MIDIA.menus)||[],d=$('#modal');d.innerHTML=`<form method="dialog" onsubmit="return false"><h2>Mis menús guardados</h2><div class="md-res">${ms.length?ms.map(m=>{const tot=m.items.reduce((a,x)=>a+x.kcal,0);return `<div class="md-it"><span><b>${esc(m.nombre)}</b><small>${m.items.map(x=>esc(x.nombre)).join(', ')}</small></span><i>${tot} kcal</i><button type="button" class="save" style="padding:8px 12px" onclick="miDiaUsarMenu('${m.id}')">Usar</button><button type="button" class="more" aria-label="Borrar menú" onclick="miDiaBorrarMenu('${m.id}')">×</button></div>`}).join(''):'<div class="empty">Todavía no guardaste menús. Armá una comida y tocá "Guardar como menú".</div>'}</div><div class="actions" style="margin-top:12px"><button class="cancel" type="button" onclick="$('#modal').close()">Cerrar</button></div></form>`;d.showModal()}
async function miDiaUsarMenu(id){try{await api('aplicarMenu',{id,fecha:miDiaFecha(),momento:MIDIA_MOM});$('#modal').close();say('Menú agregado');await cargarMiDia()}catch(e){say(e.message)}}
async function miDiaBorrarMenu(id){if(!confirm('¿Borrar este menú guardado?'))return;try{await api('deleteMenu',{id});await cargarMiDia();miDiaMenus(MIDIA_MOM)}catch(e){say(e.message)}}
function miDiaHtml(){if(MIDIA===null)return '<div class="empty">Cargando…</div>';const f=miDiaFecha(),esHoy=f===today(),titulo=esHoy?'Hoy':new Date(f+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long'}),items=MIDIA.items,total=items.reduce((a,x)=>a+x.kcal,0),info=calcularBalanceCalorico([]),meta=Number(AUTH?.nutricion?.calorie_goal)||0;let resumen;if(!info){resumen=`<div class="md-sum"><div><small>Calorías de ${esHoy?'hoy':'este día'}</small><b>${total} kcal</b></div><p class="md-note">Para saber si estás en déficit, completá tu peso, altura, edad, sexo y actividad en <a onclick="editarPerfilSalud()">Mis datos</a>.</p></div>`}else{const dif=total-info.tdee,pct=Math.min(100,Math.round(total/info.tdee*100));let v,cl;if(!items.length){v='Cargá lo que comiste para ver tu balance.';cl='#B7BCCB'}else if(dif<-100){v=`Déficit de ${Math.abs(dif)} kcal`;cl='#8FE0B0'}else if(dif>100){v=`Superávit de ${dif} kcal`;cl='#FF9C8F'}else{v='Mantenimiento (±100 kcal)';cl='#BFDDFB'}resumen=`<div class="md-sum"><div><small>Comiste</small><b>${total} kcal</b></div><div style="text-align:right"><small>Tu cuerpo gasta</small><b>${info.tdee} kcal</b></div></div><div class="fuga-bar" style="margin:12px 0 10px"><i style="width:${pct}%;background:${cl}"></i></div><div class="md-verd" style="color:${cl}">${v}</div><div class="md-note">Metabolismo basal: ${info.bmr} kcal (lo que gastás en reposo). Gasto del día con tu actividad: ${info.tdee} kcal.${meta?` Tu objetivo: ${meta} kcal${total?` · te ${total>meta?'pasaste por '+(total-meta):'quedan '+(meta-total)} kcal`:''}.`:''}</div>`}const bloques=MOMENTOS.map(([k,nom])=>{const its=items.filter(x=>x.momento===k),sub=its.reduce((a,x)=>a+x.kcal,0);return `<div class="fin-box md-box"><div class="md-head"><h2>${nom}</h2><span>${sub} kcal</span></div>${its.map(x=>`<div class="mov"><div class="mov-main">${esc(x.nombre)}<div class="sub">${x.cantidad!==1?x.cantidad+' × ':''}${esc(x.porcion||'')}</div></div><div class="mov-amt">${x.kcal} kcal</div><button class="more" aria-label="Quitar" onclick="miDiaBorrar('${x.id}')">×</button></div>`).join('')||'<div class="sub" style="padding:4px 0 10px">Nada cargado todavía.</div>'}<div class="md-actions"><button class="fin-go md-add" onclick="miDiaAbrir('${k}')">+ Agregar</button>${MIDIA.menus.length?`<button class="md-sec" onclick="miDiaMenus('${k}')">Mis menús</button>`:''}${its.length?`<button class="md-sec" onclick="miDiaGuardarMenu('${k}')">Guardar como menú</button>`:''}</div></div>`}).join('');return `<div class="mes-nav"><button onclick="miDiaNav(-1)" aria-label="Día anterior">‹</button><b style="text-transform:capitalize">${titulo}</b><button onclick="miDiaNav(1)" aria-label="Día siguiente">›</button></div><div class="fin-box fin-dark" style="margin-bottom:16px">${resumen}</div><div class="md-grid">${bloques}</div>`}
let NUTRI_RECETAS=null,NUTRI_PLAN=null,NUTRI_FILTROS={meal_type:'',diet:'',prep_level:'',q:''},NUTRI_PICK=null,NUTRI_TAB='miDia',NUTRI_LISTA=null,NUTRI_MEALPREP=null;
async function cargarNutricion(){if(MIDIA===null&&NUTRI_TAB==='miDia')cargarMiDia();try{const [recetas,plan]=await Promise.all([api('listRecetas'),api('getPlanSemanal')]);NUTRI_RECETAS=recetas;NUTRI_PLAN=plan}catch(e){NUTRI_RECETAS=[];NUTRI_PLAN={plan:null,comidas:[]};say(e.message)}if(view==='nutricion')render()}
function nutriTab(t){NUTRI_TAB=t;render();if(t==='miDia'&&MIDIA===null)cargarMiDia();if(t==='compras'&&NUTRI_LISTA===null)cargarListaCompras();if(t==='mealprep'&&NUTRI_MEALPREP===null)cargarMealPrep()}
function nutriComidaRow(day,tipo,comidas){const c=comidas.find(x=>x.day_of_week===day&&x.meal_type===tipo);const valor=c?(c.recipe_id?c.title:(c.texto_libre||'')):'';const esReceta=!!(c&&c.recipe_id);return `<div class="nutri-row"><div class="nutri-row-tipo">${tipo}</div><div class="nutri-row-main"><input class="nutri-row-input" placeholder="Ej: Milanesas con puré" value="${esc(valor)}" ${esReceta?'readonly onclick="abrirDetalleReceta(\''+c.recipe_id+'\')"':''} onchange="guardarComidaTextoUI(${day},'${tipo}',this.value)"><button class="nutri-row-platos" onclick="abrirSelectorReceta(${day},'${tipo}')" aria-label="Elegir del recetario"><svg viewBox="0 0 24 24"><path d="M4 12h4l2-7 4 14 2-7h4"/></svg></button>${c?`<button class="nutri-row-clear" onclick="quitarComidaUI('${c.id}')" aria-label="Quitar">✕</button>`:''}</div></div>`}
function calcularBalanceCalorico(comidas){const s=AUTH?.settings||{};const sortedPesos=DB.pesos.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha));const pesoKg=sortedPesos.length?Number(sortedPesos[0].kg):null;const alturaCm=s.altura_cm?Number(s.altura_cm):null;const edad=s.edad?Number(s.edad):null;const sexo=s.sexo||null;const actividad=s.nivel_actividad||null;if(!pesoKg||!alturaCm||!edad||!sexo||!actividad)return null;const bmr=sexo==='f'?(10*pesoKg+6.25*alturaCm-5*edad-161):(10*pesoKg+6.25*alturaCm-5*edad+5);const factores={sedentario:1.2,ligero:1.375,moderado:1.55,activo:1.725,muy_activo:1.9};const tdee=Math.round(bmr*factores[actividad]);const porDia={};comidas.forEach(c=>{if(c.calories_per_serving)porDia[c.day_of_week]=(porDia[c.day_of_week]||0)+c.calories_per_serving});const dias=Object.keys(porDia);const promedio=dias.length?Math.round(dias.reduce((sum,d)=>sum+porDia[d],0)/dias.length):null;return {bmr:Math.round(bmr),tdee,promedio,diasConDatos:dias.length}}
function nutriBalanceHtml(comidas){const b=calcularBalanceCalorico(comidas);if(!b)return `<div class="card" style="margin-bottom:14px"><b>Balance calórico</b><p class="sub" style="margin:6px 0 0">Completá peso (en Cuerpo), y altura, edad, sexo y nivel de actividad en <a onclick="editarPerfilSalud()" style="color:var(--violet);cursor:pointer;font-weight:700">Mis datos</a> para ver si tu semana está en déficit, mantenimiento o superávit.</p></div>`;let veredicto,color;if(b.promedio==null){veredicto='Asigná comidas del recetario (con calorías) para calcular tu promedio diario.';color='var(--muted)'}else{const dif=b.promedio-b.tdee;if(dif<-100){veredicto=`Déficit de ~${Math.abs(dif)} kcal/día`;color='var(--violet)'}else if(dif>100){veredicto=`Superávit de ~${dif} kcal/día`;color='var(--pink)'}else{veredicto='Mantenimiento (± 100 kcal/día)';color='var(--accent)'}}return `<div class="card" style="margin-bottom:14px"><b>Balance calórico</b><div style="display:flex;gap:18px;flex-wrap:wrap;margin:10px 0 4px"><div><small class="sub" style="display:block">Metabolismo basal</small><b>${b.bmr} kcal</b></div><div><small class="sub" style="display:block">Gasto diario estimado</small><b>${b.tdee} kcal</b></div><div><small class="sub" style="display:block">Promedio planificado</small><b>${b.promedio!=null?b.promedio+' kcal':'—'}</b></div></div><p class="sub" style="margin:4px 0 0;color:${color};font-weight:700">${veredicto}</p>${b.promedio!=null&&b.diasConDatos<7?`<p class="sub" style="margin:4px 0 0">Solo cuenta días con comidas del recetario (con calorías cargadas); el texto libre no suma calorías. Calculado sobre ${b.diasConDatos} de 7 días.</p>`:''}</div>`}
function nutriPlanHtml(DIAS,TIPOS,comidas){const dietChips=`<div class="chip-group" style="margin:0 0 4px">${[['','Cualquier dieta'],['vegetariano','Vegetariana'],['vegano','Vegana'],['sin_tacc','Sin TACC'],['keto','Keto']].map(([v,l])=>`<button class="chip ${NUTRI_FILTROS.diet===v?'on':''}" onclick="NUTRI_FILTROS.diet='${v}';render()">${l}</button>`).join('')}</div>`;const hoy=new Date().getDay();return `<div class="card" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px"><b>Generar semana</b><button class="link" onclick="generarSemanaRandomUI()">Generar aleatoriamente</button></div>${dietChips}<p class="sub" style="margin:6px 0 0">La dieta elegida filtra el recetario y "Generar aleatoriamente".</p></div>${nutriBalanceHtml(comidas)}${DIAS.map((nombre,d)=>`<details class="mod-sec" ${d===hoy?'open':''}><summary><h2>${nombre}</h2></summary><div class="mod-sec-body">${TIPOS.map(tipo=>nutriComidaRow(d,tipo,comidas)).join('')}</div></details>`).join('')}<div style="display:flex;gap:10px;margin-top:14px"><button class="link" style="flex:1;border:1px solid var(--line);border-radius:13px;padding:11px;text-align:center" onclick="enviarMenuWhatsAppUI()">Enviar por WhatsApp</button><button class="link" style="flex:1;border:1px solid var(--line);border-radius:13px;padding:11px;text-align:center" onclick="descargarMenuPDF()">Descargar PDF</button></div>`}
function nutriRecetarioHtml(){let recetasFiltradas=NUTRI_RECETAS.filter(r=>{if(NUTRI_FILTROS.meal_type&&r.meal_type!==NUTRI_FILTROS.meal_type)return false;if(NUTRI_FILTROS.diet&&!(r.diet_tags||[]).includes(NUTRI_FILTROS.diet))return false;if(NUTRI_FILTROS.prep_level&&r.prep_level!==Number(NUTRI_FILTROS.prep_level))return false;if(NUTRI_FILTROS.q&&!r.title.toLowerCase().includes(NUTRI_FILTROS.q.toLowerCase()))return false;return true});return `<input class="nutri-search" placeholder="Buscar receta..." value="${esc(NUTRI_FILTROS.q||'')}" oninput="NUTRI_FILTROS.q=this.value;render()"><div class="chip-group">${[['','Todas'],['desayuno','Desayuno'],['almuerzo','Almuerzo'],['merienda','Merienda'],['cena','Cena'],['snack','Snack']].map(([v,l])=>`<button class="chip ${NUTRI_FILTROS.meal_type===v?'on':''}" onclick="NUTRI_FILTROS.meal_type='${v}';render()">${l}</button>`).join('')}</div><div class="chip-group">${[['','Cualquier dieta'],['vegetariano','Vegetariano'],['vegano','Vegano'],['sin_tacc','Sin TACC'],['pescetariano','Pescetariano'],['keto','Keto']].map(([v,l])=>`<button class="chip ${NUTRI_FILTROS.diet===v?'on':''}" onclick="NUTRI_FILTROS.diet='${v}';render()">${l}</button>`).join('')}</div><div class="chip-group">${[['','Cualquier tiempo'],['15','15 min'],['45','45 min'],['90','90 min']].map(([v,l])=>`<button class="chip ${String(NUTRI_FILTROS.prep_level||'')===v?'on':''}" onclick="NUTRI_FILTROS.prep_level='${v}';render()">${l}</button>`).join('')}</div><p class="sub" style="margin:10px 2px">${recetasFiltradas.length} recetas</p>${recetasFiltradas.map(r=>`<div class="item" onclick="abrirDetalleReceta('${r.id}')"><div class="item-main"><b>${esc(r.title)}</b><div class="sub">${r.meal_type} · ${r.prep_level} min${r.calories_per_serving?' · '+r.calories_per_serving+' kcal':''}</div></div><button class="more" aria-label="Ver receta">→</button></div>`).join('')||'<div class="empty">No hay recetas con esos filtros.</div>'}`}
const NUTRI_SECCION_IDS={'Verduras y Frutas':1,'Carnes y Pescados':2,'Lácteos y Huevos':3,'Almacén':4,'Panadería':5,'Congelados':6,'Bebidas':7,'Limpieza':8,'Otros':9};
function nutriComprasHtml(){if(NUTRI_LISTA===null)return '<div class="empty">Cargando…</div>';const porSeccion={};NUTRI_LISTA.forEach(i=>{(porSeccion[i.seccion]=porSeccion[i.seccion]||[]).push(i)});const orden=Object.keys(NUTRI_SECCION_IDS).concat(Object.keys(porSeccion).filter(s=>!(s in NUTRI_SECCION_IDS))).filter(s=>porSeccion[s]&&porSeccion[s].length);return `<div style="display:flex;justify-content:flex-end;margin-bottom:10px"><button class="link" onclick="vaciarListaUI()">Vaciar</button></div>${orden.length?orden.map(s=>`<div class="card" style="margin-bottom:12px"><b>${esc(s)}</b>${porSeccion[s].map(i=>`<div class="item"><button class="check ${i.hecho?'done':''}" aria-label="${i.hecho?'Desmarcar':'Marcar'}" onclick="toggleListaItemUI('${i.key}',${i.manual?'true':'false'},'${i.manual?i.id:''}',${i.hecho?'true':'false'})">${i.hecho?'✓':''}</button><div class="item-main ${i.hecho?'strike':''}">${esc(i.name)}${i.quantity?' — '+i.quantity+' '+(i.unit||''):''}</div>${i.manual?`<button class="more" onclick="eliminarItemListaUI('${i.id}')" aria-label="Eliminar">✕</button>`:''}</div>`).join('')}<div class="nutri-add-row"><input placeholder="+ Agregar item (Enter)" onkeydown="if(event.key==='Enter'){agregarItemListaUI(${NUTRI_SECCION_IDS[s]||9},this);event.preventDefault()}"></div></div>`).join(''):'<div class="empty">Se arma sola con lo que planifiques en la semana, o agregá items a mano.</div>'}`}
async function cargarListaCompras(){try{NUTRI_LISTA=await api('getListaCompras')}catch(e){NUTRI_LISTA=[];say(e.message)}if(view==='nutricion')render()}
async function agregarItemListaUI(seccionId,input){const texto=input.value.trim();if(!texto)return;busy(1);try{await api('agregarItemLista',{store_section_id:seccionId,texto});input.value='';await cargarListaCompras()}catch(e){say(e.message)}busy(0)}
async function eliminarItemListaUI(id){busy(1);try{await api('eliminarItemLista',{id});await cargarListaCompras()}catch(e){say(e.message)}busy(0)}
async function vaciarListaUI(){if(!confirm('¿Vaciar la lista de compras?'))return;busy(1);try{await api('vaciarLista',{});await cargarListaCompras()}catch(e){say(e.message)}busy(0)}
function nutriMealPrepHtml(){if(NUTRI_MEALPREP===null)return '<div class="empty">Cargando…</div>';const NIVELES=[[1,'Mínimo viable','15-20 min'],[2,'Modo estándar','45-60 min'],[3,'Modo pro','90+ min']];return `<div style="display:flex;justify-content:flex-end;margin-bottom:10px"><button class="link" onclick="vaciarMealPrepUI()">Vaciar</button></div>${NIVELES.map(([n,label,tiempo])=>{const tareas=NUTRI_MEALPREP.filter(t=>t.nivel===n);return `<div class="card" style="margin-bottom:12px"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap"><span class="chip on" style="cursor:default">NIVEL ${n}</span><b>${label}</b><span class="sub">${tiempo}</span></div>${tareas.map(t=>`<div class="item"><button class="check ${t.hecho?'done':''}" aria-label="${t.hecho?'Desmarcar':'Marcar'}" onclick="toggleMealPrepUI('${t.id}',${t.hecho?'true':'false'})">${t.hecho?'✓':''}</button><div class="item-main ${t.hecho?'strike':''}">${esc(t.texto)}</div><button class="more" onclick="eliminarMealPrepUI('${t.id}')" aria-label="Eliminar">✕</button></div>`).join('')||'<div class="empty">Sin tareas todavía.</div>'}<div class="nutri-add-row"><input placeholder="+ Agregar tarea (Enter)" onkeydown="if(event.key==='Enter'){agregarMealPrepUI(${n},this);event.preventDefault()}"></div></div>`}).join('')}`}
async function cargarMealPrep(){try{NUTRI_MEALPREP=await api('getMealPrep')}catch(e){NUTRI_MEALPREP=[];say(e.message)}if(view==='nutricion')render()}
async function agregarMealPrepUI(nivel,input){const texto=input.value.trim();if(!texto)return;busy(1);try{await api('agregarMealPrepTask',{nivel,texto});input.value='';await cargarMealPrep()}catch(e){say(e.message)}busy(0)}
async function toggleMealPrepUI(id,hecho){busy(1);try{await api('toggleMealPrepTask',{id,hecho:!hecho});await cargarMealPrep()}catch(e){say(e.message)}busy(0)}
async function eliminarMealPrepUI(id){busy(1);try{await api('eliminarMealPrepTask',{id});await cargarMealPrep()}catch(e){say(e.message)}busy(0)}
async function vaciarMealPrepUI(){if(!confirm('¿Vaciar meal prep?'))return;busy(1);try{await api('vaciarMealPrep',{});await cargarMealPrep()}catch(e){say(e.message)}busy(0)}
function abrirSelectorReceta(day,tipo){NUTRI_PICK={day,tipo};const opciones=NUTRI_RECETAS.filter(r=>r.meal_type===tipo);const d=$('#modal');d.innerHTML=`<h2 style="margin:0 0 10px">Elegí ${tipo}</h2><div style="max-height:55vh;overflow-y:auto">${opciones.map(r=>`<div class="item" onclick="elegirRecetaSlot('${r.id}')"><div class="item-main"><b>${esc(r.title)}</b><div class="sub">${r.prep_level} min${r.calories_per_serving?' · '+r.calories_per_serving+' kcal':''}</div></div></div>`).join('')||'<div class="empty">No hay recetas de este tipo todavía.</div>'}</div><button class="cancel" style="width:100%;margin-top:12px" onclick="$('#modal').close()">Cancelar</button>`;d.showModal()}
async function elegirRecetaSlot(recipeId){const pick=NUTRI_PICK;$('#modal').close();busy(1);try{await api('asignarComida',{day_of_week:pick.day,meal_type:pick.tipo,recipe_id:recipeId});await cargarNutricion()}catch(e){say(e.message)}busy(0)}
async function guardarComidaTextoUI(day,tipo,texto){texto=String(texto).trim();if(!texto)return;busy(1);try{await api('asignarComida',{day_of_week:day,meal_type:tipo,texto});await cargarNutricion()}catch(e){say(e.message)}busy(0)}
async function quitarComidaUI(id){busy(1);try{await api('quitarComida',{id});await cargarNutricion()}catch(e){say(e.message)}busy(0)}
async function generarSemanaRandomUI(){busy(1,'Generando semana…');try{await api('generarSemanaRandom',{diet:NUTRI_FILTROS.diet||undefined});await cargarNutricion();say(NUTRI_FILTROS.diet?'Semana generada ('+NUTRI_FILTROS.diet+')':'Semana generada')}catch(e){say(e.message)}busy(0)}
async function abrirDetalleReceta(id){const d=$('#modal');d.innerHTML='<div class="empty">Cargando…</div>';d.showModal();try{const r=await api('getReceta',{id});d.innerHTML=`<h2 style="margin:0 0 4px">${esc(r.title)}</h2><p class="sub" style="margin:0 0 10px">${r.meal_type} · ${r.prep_level} min · ${r.servings} porciones${r.calories_per_serving?' · '+r.calories_per_serving+' kcal':''}</p>${r.description?`<p style="margin:0 0 12px">${esc(r.description)}</p>`:''}<div class="sub" style="font-weight:800;margin-bottom:6px">Ingredientes</div><ul class="ej-instrucciones" style="margin-bottom:14px">${(r.ingredientes||[]).map(i=>`<li>${i.quantity?i.quantity+' '+(i.unit||''):''} ${esc(i.name)}${i.seccion?' <span class="sub">('+esc(i.seccion)+')</span>':''}</li>`).join('')}</ul><div class="sub" style="font-weight:800;margin-bottom:6px">Preparación</div><ol class="ej-instrucciones">${(r.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><button class="cancel" style="width:100%;margin-top:12px" onclick="$('#modal').close()">Cerrar</button>`}catch(e){d.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function guardarPerfilNutricionUI(e){e.preventDefault();const fd=new FormData(e.target);try{const r=await api('guardarPerfilNutricion',{diet_type:fd.get('diet_type'),household_size:fd.get('household_size'),calorie_goal:fd.get('calorie_goal')});AUTH.nutricion={...AUTH.nutricion,...r};say('Guardado')}catch(err){say(err.message)}}
function textoMenuSemana(){const DIAS=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];const TIPOS=['desayuno','almuerzo','merienda','cena'];const comidas=(NUTRI_PLAN&&NUTRI_PLAN.comidas)||[];let lines=['MENÚ SEMANAL - VIDAPLUS',''];for(let d=0;d<7;d++){const delDia=TIPOS.map(tipo=>{const c=comidas.find(x=>x.day_of_week===d&&x.meal_type===tipo);if(!c)return null;const nombre=c.recipe_id?c.title:c.texto_libre;return nombre?'  '+tipo+': '+nombre:null}).filter(Boolean);if(delDia.length){lines.push(DIAS[d].toUpperCase());lines.push(...delDia);lines.push('')}}return lines.join('\n').trim()}
function enviarMenuWhatsAppUI(){const texto=textoMenuSemana();if(texto==='MENÚ SEMANAL - VIDAPLUS'){say('Todavía no armaste el menú de la semana');return}window.open('https://wa.me/?text='+encodeURIComponent(texto),'_blank')}
async function descargarMenuPDF(){const comidas=(NUTRI_PLAN&&NUTRI_PLAN.comidas)||[];if(!comidas.length){say('Todavía no armaste el menú de la semana');return}busy(1,'Generando PDF…');try{const DIAS=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];const TIPOS=['desayuno','almuerzo','merienda','cena'];const idsRecetas=[...new Set(comidas.filter(c=>c.recipe_id).map(c=>c.recipe_id))];const detalles={};for(const id of idsRecetas){try{detalles[id]=await api('getReceta',{id})}catch(_){}}let html='<html><head><meta charset="utf-8"><title>Menú semanal - VidaPlus</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#222}h1{margin-bottom:2px}h2{margin:26px 0 8px;border-bottom:2px solid #2F6B4F;padding-bottom:4px}h3{margin:16px 0 2px}ul,ol{margin:4px 0 10px;padding-left:20px}.sub{color:#666;font-size:13px;margin:0 0 18px}</style></head><body>';html+='<h1>Menú semanal</h1><p class="sub">VidaPlus</p>';for(let d=0;d<7;d++){const delDia=TIPOS.map(tipo=>({tipo,c:comidas.find(x=>x.day_of_week===d&&x.meal_type===tipo)})).filter(x=>x.c);if(!delDia.length)continue;html+='<h2>'+DIAS[d]+'</h2>';for(const {tipo,c} of delDia){const nombre=c.recipe_id?c.title:c.texto_libre;html+='<h3>'+tipo.toUpperCase()+': '+esc(nombre||'')+'</h3>';const r=c.recipe_id?detalles[c.recipe_id]:null;if(r){if(r.ingredientes&&r.ingredientes.length)html+='<b>Ingredientes</b><ul>'+r.ingredientes.map(i=>'<li>'+(i.quantity?i.quantity+' '+(i.unit||''):'')+' '+esc(i.name)+'</li>').join('')+'</ul>';if(r.steps&&r.steps.length)html+='<b>Preparación</b><ol>'+r.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>'}}}html+='</body></html>';const w=window.open('','_blank');if(!w){say('Habilitá las ventanas emergentes para descargar el PDF');busy(0);return}w.document.write(html);w.document.close();setTimeout(()=>{try{w.focus();w.print()}catch(_){}},350)}catch(e){say(e.message)}busy(0)}
async function foodImagePayload(file){let url=URL.createObjectURL(file),img=await new Promise((ok,bad)=>{let i=new Image();i.onload=()=>ok(i);i.onerror=bad;i.src=url}),max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height)),w=Math.round((img.naturalWidth||img.width)*scale),h=Math.round((img.naturalHeight||img.height)*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);return {image:canvas.toDataURL('image/jpeg',.76).split(',')[1],mimeType:'image/jpeg'}}
async function analyzeFoodPhoto(){let d=$('#modal'),file=d.querySelector('[name=foto]')?.files?.[0],btn=$('#foodAnalyzeBtn');if(!file)return say('Elegí o sacá una foto primero');if(btn?.disabled)return;btn.disabled=true;btn.innerHTML='<span class="mini-spin"></span>Analizando foto…';busy(1,'Analizando tu foto con IA…');try{let body=await foodImagePayload(file);if(body.image.length>3_800_000)throw Error('La foto sigue siendo muy grande; acercate al plato o usá otra foto');let r=await fetch('/api/analyze-food',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!j.ok)throw Error(j.error);let x=j.data,foods=(x.alimentos||[]).map(a=>a.nombre+(a.porcion?' ('+a.porcion+')':'')).join(', ');d.querySelector('[name=alimentos]').value=foods;['calorias','proteinas','carbohidratos','grasas','nota'].forEach(k=>{let el=d.querySelector('[name='+k+']');if(el&&x[k]!=null)el.value=x[k]});say('Estimación lista: revisala antes de guardar')}catch(e){say(e.message||'No se pudo preparar la foto')}finally{busy(0);if(btn){btn.disabled=false;btn.textContent='✦ Analizar foto con IA'}}}
function quickFoodPhoto(){openNutrition(true)}
function openNutrition(openPicker=false){let d=$('#modal');d.innerHTML=`<form method="dialog"><h2>Registrar comida</h2><label class="form-field">Foto del plato<input name="foto" type="file" accept="image/*"></label><button id="foodAnalyzeBtn" type="button" class="save" style="width:100%;padding:12px;border-radius:13px;margin:-4px 0 12px" onclick="analyzeFoodPhoto()">✦ Analizar foto con IA</button><p class="frequency-note">La imagen se envía a Gemini para analizarla y se descarta: no se guarda en VidaPlus.</p><label class="form-field">Tipo de comida<select name="tipo"><option value="Desayuno">Desayuno</option><option value="Almuerzo">Almuerzo</option><option value="Merienda">Merienda</option><option value="Cena">Cena</option><option value="Snack">Snack</option></select></label><label class="form-field">Fecha<input name="fecha" type="date" value="${today()}"></label><label class="form-field">Alimentos<textarea name="alimentos" placeholder="Ej. Pollo a la plancha, arroz y ensalada"></textarea></label><label class="form-field">Calorías estimadas<input name="calorias" type="number" min="0" placeholder="Ej. 550"></label><label class="form-field">Proteínas (g)<input name="proteinas" type="number" min="0" step="0.1"></label><label class="form-field">Carbohidratos (g)<input name="carbohidratos" type="number" min="0" step="0.1"></label><label class="form-field">Grasas (g)<input name="grasas" type="number" min="0" step="0.1"></label><label class="form-field">Nota<input name="nota" placeholder="Opcional"></label><div class="actions"><button class="cancel" value="cancel" formnovalidate>Cancelar</button><button class="save" value="save">Guardar comida</button></div></form>`;d.showModal();if(openPicker)setTimeout(()=>d.querySelector('[name=foto]')?.click(),120);d.onclose=async()=>{if(d.returnValue!=='save')return;let p=Object.fromEntries(new FormData(d.querySelector('form')));p.alimentos=String(p.alimentos||'').split(',').map(nombre=>({nombre:nombre.trim()})).filter(x=>x.nombre);delete p.foto;act('addComida',p,'Comida registrada')}}
